# Generated by Django 5.0.2 on 2025-05-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='physical_examination',
            field=models.JSONField(blank=True, default=dict, help_text='Physical examination findings'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vital_signs',
            field=models.JSONField(blank=True, default=dict, help_text='Vital signs data (temperature, blood pressure, etc.)'),
        ),
    ]
