# Generated by Django 5.0.2 on 2026-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_medicalrecord_concern'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
