# Generated by manual update on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_medicalrecord_diagnosis_enc_patient_first_name_enc_and_more'),
    ]

    operations = [
        # Use SeparateDatabaseAndState for defensive field additions
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='dentalrecord',
                    name='concern',
                    field=models.TextField(blank=True, help_text="Student's concern / reason for visit"),
                ),
                migrations.AddField(
                    model_name='dentalrecord',
                    name='referral_to',
                    field=models.TextField(blank=True, help_text='Referral to other clinic or specialist'),
                ),
                migrations.AddField(
                    model_name='consultation',
                    name='concern',
                    field=models.TextField(blank=True, help_text="Student's concern / reason for visit"),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$ 
                    BEGIN 
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='patients_dentalrecord' AND column_name='concern') THEN
                            ALTER TABLE patients_dentalrecord ADD COLUMN concern text DEFAULT '';
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='patients_dentalrecord' AND column_name='referral_to') THEN
                            ALTER TABLE patients_dentalrecord ADD COLUMN referral_to text DEFAULT '';
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='patients_consultation' AND column_name='concern') THEN
                            ALTER TABLE patients_consultation ADD COLUMN concern text DEFAULT '';
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    ALTER TABLE patients_dentalrecord DROP COLUMN IF EXISTS concern;
                    ALTER TABLE patients_dentalrecord DROP COLUMN IF EXISTS referral_to;
                    ALTER TABLE patients_consultation DROP COLUMN IF EXISTS concern;
                    """
                ),
            ]
        ),
        migrations.AlterField(
            model_name='dentalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Dental diagnosis and findings'),
        ),
        migrations.AlterField(
            model_name='dentalrecord',
            name='procedure_performed',
            field=models.CharField(choices=[('CONSULTATION', 'Dental Consultation'), ('REFERRAL', 'Referral'), ('CLEANING', 'Dental Cleaning'), ('FILLING', 'Dental Filling'), ('EXTRACTION', 'Tooth Extraction'), ('ROOT_CANAL', 'Root Canal Treatment'), ('CROWN', 'Crown Placement'), ('BRIDGE', 'Bridge Work'), ('IMPLANT', 'Dental Implant'), ('ORTHODONTIC', 'Orthodontic Treatment'), ('PERIODONTAL', 'Periodontal Treatment'), ('PROPHYLAXIS', 'Prophylaxis'), ('FLUORIDE', 'Fluoride Treatment'), ('SEALANT', 'Dental Sealant'), ('WHITENING', 'Teeth Whitening'), ('XRAY', 'Dental X-Ray'), ('OTHER', 'Other Procedure')], default='CONSULTATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='dentalrecord',
            name='treatment_performed',
            field=models.TextField(blank=True, help_text='Treatment performed during this visit'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='chief_complaints',
            field=models.TextField(blank=True),
        ),
    ]
