# Generated by Django 5.0.2 on 2026-05-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_simplify_dental_and_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalrecord',
            name='feedback_email_sent',
            field=models.BooleanField(default=False, help_text='Track if feedback request email was sent'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='feedback_email_sent',
            field=models.BooleanField(default=False, help_text='Track if feedback request email was sent'),
        ),
    ]
