# Generated by Django 5.0.2 on 2026-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_dentalrecord_feedback_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalrecord',
            name='feedback_reminder_sent',
            field=models.BooleanField(default=False, help_text='Track if 24-hour feedback reminder email was sent'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='feedback_reminder_sent',
            field=models.BooleanField(default=False, help_text='Track if 24-hour feedback reminder email was sent'),
        ),
        migrations.AlterField(
            model_name='dentalrecord',
            name='feedback_email_sent',
            field=models.BooleanField(default=False, help_text='Track if immediate feedback request email was sent'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='feedback_email_sent',
            field=models.BooleanField(default=False, help_text='Track if immediate feedback request email was sent'),
        ),
    ]
