# Generated by Django 5.0.2 on 2026-05-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_dentalrecord_feedback_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalrecord',
            name='procedure_performed',
            field=models.CharField(choices=[('CONSULTATION', 'Dental Consultation'), ('REFERRAL', 'Referral'), ('OTHER', 'Other Procedure')], default='CONSULTATION', max_length=20),
        ),
    ]
