# Generated by Django 5.0.2 on 2026-05-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_dentalrecord_procedure_performed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalrecord',
            name='occlusion',
            field=models.CharField(blank=True, help_text='Bite/Alignment assessment', max_length=100),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='periodontal_screening',
            field=models.CharField(blank=True, help_text='PSR or general gum health summary', max_length=100),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='soft_tissue_exam',
            field=models.TextField(blank=True, help_text='Findings on tongue, cheeks, floor of mouth, etc.'),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='tmd_assessment',
            field=models.CharField(blank=True, help_text='Temporomandibular joint assessment', max_length=100),
        ),
    ]
