# Generated by Django 5.2.4 on 2025-07-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_user_indexes'),
        ('authentication', '0003_create_default_admin'),
    ]

    operations = [
    ]
