# Generated by Django 5.0.2 on 2025-09-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_dentist_role_and_pgcrypto_fields'),
        ('authentication', '0004_merge_0002_add_user_indexes_0003_create_default_admin'),
    ]

    operations = [
    ]
