# Generated by Django 5.0.2 on 2026-02-14 16:39

from django.db import migrations
from django.contrib.postgres.operations import CryptoExtension

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20250910_0047'),
    ]

    operations = [
        CryptoExtension(),
    ]
