# Generated by Django 5.0.2 on 2026-04-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_safeemail_user_is_verified_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeemail',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('DENTIST', 'Dentist'), ('NURSE', 'Nurse'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', help_text='Role to automatically assign when this user registers', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('DENTIST', 'Dentist'), ('NURSE', 'Nurse'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=10, null=True),
        ),
    ]
