# Generated by Django 5.0.2 on 2026-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_teacher_to_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_type_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
