# Generated by Django 5.0.2 on 2026-05-29 07:35

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=200)),
                ('username', models.CharField(db_index=True, max_length=200)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('DENTIST', 'Dentist'), ('NURSE', 'Nurse'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty')], default='STUDENT', max_length=10)),
                ('requested_role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('DENTIST', 'Dentist'), ('NURSE', 'Nurse'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty')], max_length=10, null=True)),
                ('completeSetup', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('year_level', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('address_permanent', models.CharField(blank=True, max_length=300, null=True)),
                ('address_present', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('bmi', models.CharField(blank=True, max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number_enc', models.BinaryField(blank=True, null=True)),
                ('illness', models.CharField(blank=True, max_length=100, null=True)),
                ('childhood_diseases', models.CharField(blank=True, max_length=100, null=True)),
                ('special_needs', models.CharField(blank=True, max_length=100, null=True)),
                ('existing_medical_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('medications', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('hospitalization_history', models.CharField(blank=True, max_length=100, null=True)),
                ('surgical_procedures', models.CharField(blank=True, max_length=100, null=True)),
                ('illness_enc', models.BinaryField(blank=True, null=True)),
                ('existing_medical_condition_enc', models.BinaryField(blank=True, null=True)),
                ('medications_enc', models.BinaryField(blank=True, null=True)),
                ('allergies_enc', models.BinaryField(blank=True, null=True)),
                ('blood_type_enc', models.BinaryField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
