# Generated by Django 5.0.2 on 2026-03-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('PATIENT_SUMMARY', 'Patient Summary Report'), ('VISIT_TRENDS', 'Visit Trends Report'), ('TREATMENT_OUTCOMES', 'Treatment Outcomes Report'), ('MEDICAL_STATISTICS', 'Medical Statistics Report'), ('DENTAL_STATISTICS', 'Dental Statistics Report'), ('FEEDBACK_ANALYSIS', 'Feedback Analysis Report'), ('CAMPAIGN_PERFORMANCE', 'Campaign Performance Report'), ('USER_ACTIVITY', 'User Activity Report'), ('HEALTH_METRICS', 'Health Metrics Report'), ('COMPLIANCE_REPORT', 'Compliance Report')], max_length=25),
        ),
    ]
