# Generated by Django 5.0.2 on 2026-03-25 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reporttemplate_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='file_path',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'csv', 'json', 'html'])]),
        ),
    ]
