# Generated by Django 5.0.2 on 2026-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_reporttemplate_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('PATIENT_SUMMARY', 'Patient Summary Report'), ('VISIT_TRENDS', 'Visit Trends Report'), ('TREATMENT_OUTCOMES', 'Treatment Outcomes Report'), ('MEDICAL_STATISTICS', 'Medical Statistics Report'), ('DENTAL_STATISTICS', 'Dental Statistics Report'), ('FEEDBACK_ANALYSIS', 'Feedback Analysis Report'), ('CAMPAIGN_PERFORMANCE', 'Campaign Performance Report'), ('USER_ACTIVITY', 'User Activity Report'), ('OPERATIONS', 'Clinic Operations Report'), ('HEALTH_METRICS', 'Health Metrics Report'), ('HEALTH_HISTORY', 'Unified Health History Report'), ('MEDICAL_CERTIFICATE', 'Medical Fitness & Certification Report')], max_length=25),
        ),
    ]
