# Generated by Django 5.0.2 on 2025-07-04 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_dentalrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('medication_reminders', models.BooleanField(default=True)),
                ('health_campaigns', models.BooleanField(default=True)),
                ('clinic_updates', models.BooleanField(default=True)),
                ('follow_up_reminders', models.BooleanField(default=True)),
                ('vaccination_reminders', models.BooleanField(default=True)),
                ('dental_reminders', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('desktop_notifications', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Digest'), ('WEEKLY', 'Weekly Digest'), ('NEVER', 'Never')], default='IMMEDIATE', max_length=10)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_start_time', models.TimeField(blank=True, help_text='Start of quiet hours (e.g., 22:00)', null=True)),
                ('quiet_end_time', models.TimeField(blank=True, help_text='End of quiet hours (e.g., 08:00)', null=True)),
                ('language_preference', models.CharField(default='en', help_text='Language for notifications', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('FOLLOW_UP', 'Follow-up Reminder'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('DENTAL_REMINDER', 'Dental Checkup Reminder'), ('CUSTOM', 'Custom Notification')], max_length=30)),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_variables', models.JSONField(default=dict, help_text='JSON object documenting available template variables')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('FOLLOW_UP', 'Follow-up Reminder'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('DENTAL_REMINDER', 'Dental Checkup Reminder'), ('CUSTOM', 'Custom Notification')], max_length=30)),
                ('audience_type', models.CharField(choices=[('ALL_USERS', 'All Users'), ('ALL_PATIENTS', 'All Patients'), ('ROLE_BASED', 'Role Based'), ('CUSTOM_LIST', 'Custom List'), ('PATIENT_CONDITION', 'Based on Patient Condition')], max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='List of user roles to target')),
                ('custom_subject', models.CharField(blank=True, max_length=255)),
                ('custom_message', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('FOLLOW_UP', 'Follow-up Reminder'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('DENTAL_REMINDER', 'Dental Checkup Reminder'), ('CUSTOM', 'Custom Notification'), ('SYSTEM_ALERT', 'System Alert')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App'), ('BOTH', 'Both Email and In-App')], default='BOTH', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_url', models.URLField(blank=True, help_text='URL for notification action')),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('RETRY', 'Retry Attempt')], max_length=15)),
                ('details', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('email_message_id', models.CharField(blank=True, max_length=255)),
                ('email_provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['notification', 'action'], name='notificatio_notific_d42cfb_idx'), models.Index(fields=['timestamp'], name='notificatio_timesta_eacc48_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'scheduled_at'], name='notificatio_notific_32c120_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_a9c93f_idx'),
        ),
    ]
