# Generated by Django 5.1.7 on 2025-07-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='URL for notification action', null=True),
        ),
    ]
