# Generated by Django 5.1.7 on 2025-07-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_action_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, help_text='Text for action button', max_length=100, null=True),
        ),
    ]
