# Generated by Django 5.0.2 on 2026-04-20 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_action_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_emails_enabled', models.BooleanField(default=True, help_text='Master switch to enable/disable all automated emails')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Email Setting',
                'verbose_name_plural': 'Global Email Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemEmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ROLE_REQUEST', 'Role Upgrade Request'), ('NEW_REGISTRATION', 'New User Registration'), ('MEDICAL_CERTIFICATE_APPROVED', 'Medical Certificate Approved'), ('MEDICAL_CERTIFICATE_REJECTED', 'Medical Certificate Rejected'), ('SYSTEM_HEALTH_ALERT', 'System Health Alert'), ('FEEDBACK_REQUEST', 'Patient Feedback Request')], max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="List of roles that should receive this notification (e.g., ['ADMIN'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excluded_users', models.ManyToManyField(blank=True, help_text='Specific users to ALWAYS exclude for this event', related_name='excluded_from_system_emails', to=settings.AUTH_USER_MODEL)),
                ('included_users', models.ManyToManyField(blank=True, help_text='Specific users to ALWAYS include for this event', related_name='included_in_system_emails', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'System Email Configuration',
                'verbose_name_plural': 'System Email Configurations',
            },
        ),
    ]
