# Generated by Django 5.0.2 on 2026-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_globalemailsettings_systememailconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('FOLLOW_UP', 'Follow-up Reminder'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('DENTAL_REMINDER', 'Dental Checkup Reminder'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('CUSTOM', 'Custom Notification'), ('SYSTEM_ALERT', 'System Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('FOLLOW_UP', 'Follow-up Reminder'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('DENTAL_REMINDER', 'Dental Checkup Reminder'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('CUSTOM', 'Custom Notification')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('FOLLOW_UP', 'Follow-up Reminder'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('DENTAL_REMINDER', 'Dental Checkup Reminder'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('CUSTOM', 'Custom Notification')], max_length=30),
        ),
    ]
