# Generated by Django 5.0.2 on 2026-05-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Delivered'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Delivered'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('RETRY', 'Retry Attempt')], max_length=15),
        ),
        migrations.AlterField(
            model_name='systememailconfiguration',
            name='event_type',
            field=models.CharField(choices=[('ROLE_REQUEST', 'Role Upgrade Request'), ('NEW_REGISTRATION', 'New User Registration'), ('MEDICAL_CERTIFICATE_ISSUED', 'Medical Certificate Issued'), ('MEDICAL_CERTIFICATE_REJECTED', 'Medical Certificate Rejected'), ('SYSTEM_HEALTH_ALERT', 'System Health Alert'), ('FEEDBACK_REQUEST', 'Patient Feedback Request')], max_length=50, unique=True),
        ),
    ]
