# Generated by Django 5.0.2 on 2026-06-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('FOLLOW_UP', 'Follow-up Reminder'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('DENTAL_REMINDER', 'Dental Checkup Reminder'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('DOWNLOAD', 'File Download'), ('CUSTOM', 'Custom Notification'), ('SYSTEM_ALERT', 'System Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('FOLLOW_UP', 'Follow-up Reminder'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('DENTAL_REMINDER', 'Dental Checkup Reminder'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('DOWNLOAD', 'File Download'), ('CUSTOM', 'Custom Notification')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('FOLLOW_UP', 'Follow-up Reminder'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('DENTAL_REMINDER', 'Dental Checkup Reminder'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('DOWNLOAD', 'File Download'), ('CUSTOM', 'Custom Notification')], max_length=30),
        ),
    ]
