# Generated by Django 5.0.2 on 2026-06-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('MEDICAL_RECORD', 'Medical Record'), ('DENTAL_RECORD', 'Dental Record'), ('LABORATORY_RESULT', 'Laboratory Result'), ('DOWNLOAD', 'File Download'), ('SYSTEM_ALERT', 'System Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('MEDICAL_RECORD', 'Medical Record'), ('DENTAL_RECORD', 'Dental Record'), ('LABORATORY_RESULT', 'Laboratory Result'), ('DOWNLOAD', 'File Download'), ('SYSTEM_ALERT', 'System Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('HEALTH_CAMPAIGN', 'Health Campaign'), ('CLINIC_UPDATE', 'Clinic Update'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('MEDICAL_RECORD', 'Medical Record'), ('DENTAL_RECORD', 'Dental Record'), ('LABORATORY_RESULT', 'Laboratory Result'), ('DOWNLOAD', 'File Download'), ('SYSTEM_ALERT', 'System Alert')], max_length=30),
        ),
    ]
