# Generated by Django 5.1.7 on 2025-08-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backupstatus',
            new_name='utils_backu_started_92f379_idx',
            old_name='utils_backu_started_c74736_idx',
        ),
        migrations.RenameIndex(
            model_name='backupstatus',
            new_name='utils_backu_backup__6f0e42_idx',
            old_name='utils_backu_backup__b88d0b_idx',
        ),
        migrations.RenameIndex(
            model_name='backupstatus',
            new_name='utils_backu_status_f9f40d_idx',
            old_name='utils_backu_status_2a71b6_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealthmetric',
            new_name='utils_syste_metric__0f857e_idx',
            old_name='utils_syste_metric__a5e8f8_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealthmetric',
            new_name='utils_syste_recorde_77270e_idx',
            old_name='utils_syste_recorde_8b8994_idx',
        ),
    ]
