# Generated by Django 5.1.7 on 2025-08-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_rename_utils_backu_started_c74736_idx_utils_backu_started_92f379_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupstatus',
            name='duration_seconds_stored',
            field=models.FloatField(blank=True, help_text='Duration of backup operation in seconds', null=True),
        ),
    ]
