# Generated by Django 5.0.2 on 2025-06-03 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['uploaded_by', '-upload_date'], name='file_upload_uploade_58f165_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['checksum'], name='file_upload_checksu_d956f1_idx'),
        ),
    ]
