# Generated by Django 5.0.2 on 2026-04-21 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0002_alter_uploadedfile_options_uploadedfile_checksum_and_more'),
        ('patients', '0008_update_patient_user_cascade_and_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patient_documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(choices=[('CONSULTATION', 'Scanned Consultation'), ('MEDICAL_RECORD', 'Medical Record'), ('DENTAL_RECORD', 'Dental Record'), ('LAB_RESULT', 'Laboratory Result'), ('PRESCRIPTION', 'Prescription'), ('XRAY', 'X-Ray'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('other_type', models.CharField(blank=True, help_text="Custom document type if 'Other' is selected", max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_patient_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
