# Generated by manual fix to align model with database

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0003_patientdocument'),
        ('patients', '0001_initial'), # Adjust if needed, patients must exist
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='dental_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='patients.dentalrecord'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='patients.medicalrecord'),
        ),
    ]
