# Generated by Django 5.0.2 on 2026-04-22 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0003_patientdocument'),
        ('patients', '0008_update_patient_user_cascade_and_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='dental_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='patients.dentalrecord'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='patients.medicalrecord'),
        ),
    ]
