export const ProgramsChoices = [
  { id: 1, label: 'Bachelor of Science in Architecture', department: 'SAFAD' },
  { id: 2, label: 'Bachelor of Landscape Architecture', department: 'SAFAD' },
  { id: 3, label: 'Bachelor of Science in Interior Design', department: 'SAFAD' },
  { id: 4, label: 'Bachelor of Fine Arts major in Advertising Arts', department: 'SAFAD' },
  { id: 5, label: 'Bachelor of Fine Arts major in Cinema', department: 'SAFAD' },
  { id: 6, label: 'Bachelor of Arts in Anthropology', department: 'SAS' },
  { id: 7, label: 'Bachelor of Science in Biology', department: 'SAS' },
  { id: 8, label: 'Bachelor of Science in Marine Biology', department: 'SAS' },
  { id: 9, label: 'Bachelor of Science in Chemistry', department: 'SAS' },
  { id: 10, label: 'Bachelor of Arts in English Language Studies', department: 'SAS' },
  { id: 11, label: 'Bachelor of Arts in Literary and Cultural Studies with Creative Writing', department: 'SAS' },
  { id: 12, label: 'Bachelor of Arts in Communication major in Media', department: 'SAS' },
  { id: 13, label: 'Bachelor of Science in Computer Science', department: 'SAS' },
  { id: 14, label: 'Bachelor of Science in Information Systems', department: 'SAS' },
  { id: 15, label: 'Bachelor of Science in Information Technology', department: 'SAS' },
  { id: 16, label: 'Bachelor of Science in Applied Mathematics', department: 'SAS' },
  { id: 17, label: 'Bachelor of Philosophy', department: 'SAS' },
  { id: 18, label: 'Bachelor of Science in Applied Physics', department: 'SAS' },
  { id: 19, label: 'Bachelor of Science in Psychology', department: 'SAS' },
  { id: 20, label: 'Bachelor of Science in Nursing', department: 'SHCP' },
  { id: 21, label: 'Bachelor of Science in Nutrition and Dietetics', department: 'SHCP' },
  { id: 22, label: 'Bachelor of Science in Pharmacy', department: 'SHCP' },
  { id: 23, label: 'Bachelor of Arts in Political Science major in International Relations and Foreign Service', department: 'SOLG' },
  { id: 24, label: 'Bachelor of Arts in Political Science major in Law and Policy Studies', department: 'SOLG' },
  { id: 25, label: 'Bachelor of Science in Accountancy', department: 'SBE' },
  { id: 26, label: 'Bachelor of Science in Management Accounting', department: 'SBE' },
  { id: 27, label: 'Bachelor of Science in Business Administration major in Financial Management', department: 'SBE' },
  { id: 28, label: 'Bachelor of Science in Business Administration major in Human Resource Management', department: 'SBE' },
  { id: 29, label: 'Bachelor of Science in Business Administration major in Marketing Management', department: 'SBE' },
  { id: 30, label: 'Bachelor of Science in Business Administration major in Operations Management', department: 'SBE' },
  { id: 31, label: 'Bachelor of Science in Entrepreneurship', department: 'SBE' },
  { id: 32, label: 'Bachelor of Science in Economics', department: 'SBE' },
  { id: 33, label: 'Bachelor of Science in Hospitality Management', department: 'SBE' },
  { id: 34, label: 'Bachelor of Science in Tourism Management', department: 'SBE' },
  { id: 35, label: 'Diploma in Culinary Arts', department: 'SBE' },
  { id: 36, label: 'Bachelor of Secondary Education major in Science', department: 'SED' },
  { id: 37, label: 'Bachelor of Special Needs Education specialization in Early Childhood Education-Montessori Education', department: 'SED' },
  { id: 38, label: 'Bachelor of Science in Chemical Engineering', department: 'SOE' },
  { id: 39, label: 'Bachelor of Science in Civil Engineering', department: 'SOE' },
  { id: 40, label: 'Bachelor of Science in Computer Engineering', department: 'SOE' },
  { id: 41, label: 'Bachelor of Science in Electrical Engineering', department: 'SOE' },
  { id: 42, label: 'Bachelor of Science in Electronics Engineering', department: 'SOE' },
  { id: 43, label: 'Bachelor of Science in Industrial Engineering', department: 'SOE' },
  { id: 44, label: 'Bachelor of Science in Mechanical Engineering', department: 'SOE' },
  { id: 45, label: 'Doctor of Engineering', department: 'Doctoral' },
  { id: 46, label: 'Doctor of Philosophy in Biology, Track A: Bioscience', department: 'Doctoral' },
  { id: 47, label: 'Doctor of Philosophy in Business Administration', department: 'Doctoral' },
  { id: 48, label: 'Doctor of Philosophy in Education, specializations in Research and Evaluation', department: 'Doctoral' },
  { id: 49, label: 'Doctor of Philosophy in Information Technology', department: 'Doctoral' },
  { id: 50, label: 'Doctor of Philosophy in Philosophy', department: 'Doctoral' },
  { id: 51, label: 'Doctor of Philosophy in Physics', department: 'Doctoral' },
  { id: 52, label: 'Doctor of Philosophy in Science Education, major in Biology Education, Chemistry Education, or Physics Education', department: 'Doctoral' },
  { id: 53, label: 'Juris Doctor', department: 'Masteral' },
  { id: 54, label: 'Master of Business Administration', department: 'Masteral' },
  { id: 55, label: 'Master of Management, major in Hospitality Management, Management Accounting, Tourism Management', department: 'Masteral' },
  { id: 56, label: 'Master of Architecture, major in Architectural Science, Interior Architecture, Landscape Architecture, or Urban Design', department: 'Masteral' },
  { id: 57, label: 'Master of Arts in Anthropology', department: 'Masteral' },
  { id: 58, label: 'Master of Arts in Applied Linguistics', department: 'Masteral' },
  { id: 59, label: 'Master of Arts in Clinical Psychology', department: 'Masteral' },
  { id: 60, label: 'Master of Arts in Economics', department: 'Masteral' },
  { id: 61, label: 'Master of Arts in Education, major in Special Education', department: 'Masteral' },
  { id: 62, label: 'Master of Arts in Literature', department: 'Masteral' },
  { id: 63, label: 'Master of Arts in Philosophy', department: 'Masteral' },
  { id: 64, label: 'Master of Arts in Political Science', department: 'Masteral' },
  { id: 65, label: 'Master of Science in Biology', department: 'Masteral' },
  { id: 66, label: 'Master of Science in Chemical Engineering', department: 'Masteral' },
  { id: 67, label: 'Master of Science in Chemistry', department: 'Masteral' },
  { id: 68, label: 'Master of Science in Computer Engineering', department: 'Masteral' }
];

export const CivilStatusChoices = [
  { id: 1, label: 'Single' },
  { id: 2, label: 'Married' },
  { id: 3, label: 'Widowed' },
  { id: 4, label: 'Divorced' },
  { id: 5, label: 'Separated' },
];

export const SexChoices = [
  { id: 1, label: 'Male' },
  { id: 2, label: 'Female' },
];

export const YearLevelChoices = [
  { id: 1, label: '1st Year' },
  { id: 2, label: '2nd Year' },
  { id: 3, label: '3rd Year' },
  { id: 4, label: '4th Year' },
]; 

// Campus/School options for dropdowns
export const CampusChoices = [
  { id: 'Downtown Campus', label: 'Downtown Campus' },
  { id: 'Talamban Campus', label: 'Talamban Campus' }
];
