# Generated by Django 5.1.7 on 2025-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_certificates', '0003_migrate_existing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='fitness_reason',
            field=models.TextField(blank=True, help_text="Reason for fitness status, especially important for 'Not Fit' determinations"),
        ),
    ]
