# Generated by Django 5.0.2 on 2026-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_certificates', '0005_seed_default_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
    ]
