# Generated by Django 5.0.2 on 2026-05-26 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_certificates', '0006_alter_medicalcertificate_diagnosis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcertificate',
            old_name='approved_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='medicalcertificate',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='medicalcertificate',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='medicalcertificate',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='issuance_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending Issuance'), ('issued', 'Issued'), ('rejected', 'Rejected')], default='draft', help_text='Administrative issuance status for the certificate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='issuing_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_medical_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='fitness_reason',
            field=models.TextField(blank=True, help_text="Reason for fitness status, especially important for 'Physically Unfit' determinations"),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='fitness_status',
            field=models.CharField(choices=[('physically_fit', 'Physically Fit'), ('physically_unfit', 'Physically Unfit')], default='physically_fit', help_text='Medical fitness determination: Physically Fit or Physically Unfit', max_length=20),
        ),
    ]
