# Generated by Django 5.0.2 on 2026-05-26 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_certificates', '0007_rename_approved_at_medicalcertificate_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_certificates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='issuance_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Issuance'), ('issued', 'Issued'), ('rejected', 'Rejected')], default='draft', help_text='Administrative issuance status for the certificate', max_length=20),
        ),
    ]
