# Generated by Django 5.0.2 on 2026-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_certificates', '0009_historicalcertificatetemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmedicalcertificate',
            name='fitness_status',
            field=models.CharField(choices=[('FIT', 'Physically Fit'), ('UNFIT', 'Physically Unfit')], default='physically_fit', help_text='Medical fitness determination: Physically Fit or Physically Unfit', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='fitness_status',
            field=models.CharField(choices=[('FIT', 'Physically Fit'), ('UNFIT', 'Physically Unfit')], default='physically_fit', help_text='Medical fitness determination: Physically Fit or Physically Unfit', max_length=20),
        ),
    ]
