# Generated by Django 5.0.2 on 2025-07-15 12:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0003_healthcampaign_campaignresource_campaignfeedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(help_text='Template description')),
                ('campaign_type', models.CharField(choices=[('VACCINATION', 'Vaccination Campaign'), ('MENTAL_HEALTH', 'Mental Health Awareness'), ('NUTRITION', 'Nutrition & Wellness'), ('DENTAL_HEALTH', 'Dental Health'), ('HYGIENE', 'Personal Hygiene'), ('EXERCISE', 'Physical Exercise'), ('SAFETY', 'Health & Safety'), ('PREVENTION', 'Disease Prevention'), ('AWARENESS', 'Health Awareness'), ('EMERGENCY', 'Emergency Health'), ('SEASONAL', 'Seasonal Health'), ('CUSTOM', 'Custom Campaign')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('title_template', models.CharField(help_text='Default title for campaigns using this template', max_length=200)),
                ('content_template', models.TextField(help_text='Default content template')),
                ('summary_template', models.CharField(help_text='Default summary template', max_length=500)),
                ('target_audience_template', models.CharField(help_text='Default target audience', max_length=200)),
                ('objectives_template', models.TextField(help_text='Default objectives')),
                ('call_to_action_template', models.CharField(help_text='Default call to action', max_length=300)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaign_templates/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='campaign_templates/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('tags_template', models.CharField(blank=True, help_text='Default tags', max_length=500)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='healthcampaign',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_info.campaigntemplate'),
        ),
        migrations.AddIndex(
            model_name='campaigntemplate',
            index=models.Index(fields=['campaign_type', 'is_active'], name='health_info_campaig_88e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntemplate',
            index=models.Index(fields=['usage_count'], name='health_info_usage_c_992d56_idx'),
        ),
    ]
