# Generated by Django 5.1.7 on 2025-07-29 04:15

import django.core.validators
import django.db.models.deletion
import health_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0004_campaigntemplate_healthcampaign_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInformationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=health_info.models.health_info_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('health_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='health_info.healthinformation')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
