# Generated by Django 5.1.7 on 2025-07-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0005_healthinformationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntemplate',
            name='campaign_type',
            field=models.CharField(choices=[('GENERAL', 'General Health Information'), ('VACCINATION', 'Vaccination Campaign'), ('MENTAL_HEALTH', 'Mental Health Awareness'), ('NUTRITION', 'Nutrition & Wellness'), ('DENTAL_HEALTH', 'Dental Health'), ('HYGIENE', 'Personal Hygiene'), ('EXERCISE', 'Physical Exercise'), ('SAFETY', 'Health & Safety'), ('PREVENTION', 'Disease Prevention'), ('AWARENESS', 'Health Awareness'), ('EMERGENCY', 'Emergency Health'), ('SEASONAL', 'Seasonal Health'), ('CUSTOM', 'Custom Campaign')], max_length=20),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('GENERAL', 'General Health Information'), ('VACCINATION', 'Vaccination Campaign'), ('MENTAL_HEALTH', 'Mental Health Awareness'), ('NUTRITION', 'Nutrition & Wellness'), ('DENTAL_HEALTH', 'Dental Health'), ('HYGIENE', 'Personal Hygiene'), ('EXERCISE', 'Physical Exercise'), ('SAFETY', 'Health & Safety'), ('PREVENTION', 'Disease Prevention'), ('AWARENESS', 'Health Awareness'), ('EMERGENCY', 'Emergency Health'), ('SEASONAL', 'Seasonal Health'), ('CUSTOM', 'Custom Campaign')], max_length=20),
        ),
    ]
