# Generated by Django 5.0.2 on 2025-08-17 02:13

import django.core.validators
import health_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0006_add_general_campaign_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignresource',
            name='file',
            field=models.FileField(storage=health_info.models.get_media_storage, upload_to='campaign_resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, storage=health_info.models.get_media_storage, upload_to='campaign_templates/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, storage=health_info.models.get_media_storage, upload_to='campaign_templates/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Main banner image for the campaign', null=True, storage=health_info.models.get_media_storage, upload_to=health_info.models.banner_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='pubmat_image',
            field=models.ImageField(blank=True, help_text='PubMat (Public Material) for printing and distribution', null=True, storage=health_info.models.get_media_storage, upload_to=health_info.models.pubmat_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Thumbnail image for campaign listing', null=True, storage=health_info.models.get_media_storage, upload_to=health_info.models.campaign_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='healthinformationimage',
            name='image',
            field=models.ImageField(storage=health_info.models.get_media_storage, upload_to=health_info.models.health_info_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
