# Generated by Django 5.0.2 on 2025-08-17 02:30

import django.core.validators
import health_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0007_alter_campaignresource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignresource',
            name='file',
            field=models.FileField(upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Main banner image for the campaign', null=True, upload_to=health_info.models.banner_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='pubmat_image',
            field=models.ImageField(blank=True, help_text='PubMat (Public Material) for printing and distribution', null=True, upload_to=health_info.models.pubmat_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Thumbnail image for campaign listing', null=True, upload_to=health_info.models.campaign_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='healthinformationimage',
            name='image',
            field=models.ImageField(upload_to=health_info.models.health_info_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]