# Generated by Django 5.1.7 on 2025-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0008_alter_campaignresource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcampaign',
            name='call_to_action',
            field=models.CharField(blank=True, help_text='What action should people take?', max_length=300),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='objectives',
            field=models.TextField(blank=True, help_text='Campaign objectives and goals'),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='summary',
            field=models.CharField(blank=True, help_text='Brief campaign summary', max_length=500),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Target audience description', max_length=200),
        ),
    ]
