# Generated by Django 5.1.7 on 2025-08-22 12:16

import django.core.validators
import health_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0009_make_campaign_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcampaign',
            name='banner_image',
            field=models.FileField(blank=True, help_text='Main banner image for the campaign', null=True, upload_to=health_info.models.banner_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='thumbnail_image',
            field=models.FileField(blank=True, help_text='Thumbnail image for campaign listing', null=True, upload_to=health_info.models.campaign_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
