# Generated by Django 5.0.2 on 2025-09-07 08:31

import django.core.validators
import health_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0010_alter_healthcampaign_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcampaign',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Main banner image for the campaign', null=True, upload_to=health_info.models.banner_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='pubmat_image',
            field=models.FileField(blank=True, help_text='PubMat (Public Material) for printing and distribution - supports PDF', null=True, upload_to=health_info.models.pubmat_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Thumbnail image for campaign listing', null=True, upload_to=health_info.models.campaign_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
