# Generated by Django 5.0.2 on 2026-03-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0011_alter_healthcampaign_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinformation',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
