# Generated by Django 5.1.1 on 2025-09-07 10:45

from django.db import migrations


def remove_status_logic(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE health_info_healthcampaign DROP COLUMN IF EXISTS status;")
        schema_editor.execute("DROP INDEX IF EXISTS health_info_status_307538_idx;")
        schema_editor.execute("DROP INDEX IF EXISTS health_info_campaig_ba74f3_idx;")
    elif schema_editor.connection.vendor == 'sqlite':
        # SQLite 3.35+ supports DROP COLUMN, but let's be safe
        try:
            schema_editor.execute("ALTER TABLE health_info_healthcampaign DROP COLUMN status;")
        except Exception:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0012_healthinformation_view_count'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='healthcampaign',
                    name='health_info_status_307538_idx',
                ),
                migrations.RemoveIndex(
                    model_name='healthcampaign',
                    name='health_info_campaig_ba74f3_idx',
                ),
                migrations.RemoveField(
                    model_name='healthcampaign',
                    name='status',
                ),
            ],
            database_operations=[
                migrations.RunPython(remove_status_logic, migrations.RunPython.noop),
            ]
        ),
    ]
