# Generated by manual update on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0012_healthinformation_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcampaign',
            name='status',
        ),
        migrations.RemoveIndex(
            model_name='healthcampaign',
            name='health_info_status_307538_idx',
        ),
        migrations.RemoveIndex(
            model_name='healthcampaign',
            name='health_info_campaig_ba74f3_idx',
        ),
        migrations.AddIndex(
            model_name='healthcampaign',
            index=models.Index(fields=['start_date'], name='health_info_start_d_a988d5_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcampaign',
            index=models.Index(fields=['campaign_type'], name='health_info_campaig_06774a_idx'),
        ),
    ]
