# Generated by manual update on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0012_healthinformation_view_count'),
    ]

    operations = [
        # Use SeparateDatabaseAndState for defensive removal
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='healthcampaign',
                    name='status',
                ),
                migrations.RemoveIndex(
                    model_name='healthcampaign',
                    name='health_info_status_307538_idx',
                ),
                migrations.RemoveIndex(
                    model_name='healthcampaign',
                    name='health_info_campaig_ba74f3_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE health_info_healthcampaign DROP COLUMN IF EXISTS status;",
                    reverse_sql="ALTER TABLE health_info_healthcampaign ADD COLUMN status varchar(15) DEFAULT 'DRAFT';"
                ),
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS health_info_status_307538_idx;",
                    reverse_sql=""
                ),
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS health_info_campaig_ba74f3_idx;",
                    reverse_sql=""
                ),
            ]
        ),
        migrations.AddIndex(
            model_name='healthcampaign',
            index=models.Index(fields=['start_date'], name='health_info_start_d_a988d5_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcampaign',
            index=models.Index(fields=['campaign_type'], name='health_info_campaig_06774a_idx'),
        ),
    ]
