# Generated by manual update on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0013_remove_healthcampaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcampaign',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='external_link',
            field=models.URLField(blank=True, help_text='External link for more information', null=True),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Contact information for inquiries', max_length=300, null=True),
        ),
    ]
