# Generated by manual update on 2026-04-25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0014_nullable_campaign_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcampaign',
            name='pubmat_image',
            field=models.FileField(blank=True, help_text='PubMat (Public Material) for printing and distribution (Images only)', null=True, upload_to='campaigns/pubmat/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
    ]
