# Generated by Django 5.0.2 on 2026-05-20 15:25

import django.core.validators
import health_info.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0015_restrict_pubmat_to_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcampaign',
            name='pubmat_image',
            field=models.FileField(blank=True, help_text='PubMat (Public Material) for printing and distribution (Images only)', null=True, upload_to=health_info.models.pubmat_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AddIndex(
            model_name='healthcampaign',
            index=models.Index(fields=['start_date'], name='health_info_start_d_a21170_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcampaign',
            index=models.Index(fields=['campaign_type'], name='health_info_campaig_41555a_idx'),
        ),
    ]
