# Generated by Django 5.0.2 on 2026-05-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0016_alter_healthcampaign_pubmat_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcampaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=15),
        ),
    ]
