# Generated by Django 5.0.2 on 2026-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0018_alter_healthcampaign_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('ARCHIVED', 'Archived'), ('COMPLETED', 'Completed')], default='POSTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalhealthcampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhealthcampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhealthcampaign',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('ARCHIVED', 'Archived'), ('COMPLETED', 'Completed')], default='POSTED', max_length=15),
        ),
    ]
