# Generated by Django 5.0.2 on 2025-04-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='courteous',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='improvement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recommend',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
