# Generated by Django 5.0.2 on 2025-07-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_courteous_feedback_improvement_and_more'),
        ('patients', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['patient', 'medical_record'], name='feedback_fe_patient_2b2717_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['patient', 'created_at'], name='feedback_fe_patient_3add36_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('medical_record__isnull', False)), fields=('patient', 'medical_record'), name='unique_feedback_per_visit'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('medical_record__isnull', True)), fields=('patient',), name='unique_general_feedback'),
        ),
    ]
