# Generated by manual update on 2026-04-25

from django.db import migrations, models
import django.db.models.deletion

def dental_feedback_db_logic(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    
    if vendor == 'postgresql':
        # Drop old constraints/indexes defensively
        schema_editor.execute("""
            ALTER TABLE feedback_feedback DROP CONSTRAINT IF EXISTS unique_feedback_per_visit;
            DROP INDEX IF EXISTS unique_feedback_per_visit;
            ALTER TABLE feedback_feedback DROP CONSTRAINT IF EXISTS unique_general_feedback;
            DROP INDEX IF EXISTS unique_general_feedback;
        """)
        
        # Add column, index, and new constraints using a single DO block for transactional safety
        schema_editor.execute("""
            DO $$ 
            BEGIN 
                -- Add column if not exists
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                               WHERE table_name='feedback_feedback' 
                               AND column_name='dental_record_id') THEN
                    ALTER TABLE feedback_feedback ADD COLUMN dental_record_id integer 
                    REFERENCES patients_dentalrecord(id) ON DELETE SET NULL;
                END IF;

                -- Add regular index if not exists
                IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace 
                               WHERE c.relname = 'feedback_fe_patient_2c8f8b_idx') THEN
                    CREATE INDEX feedback_fe_patient_2c8f8b_idx ON feedback_feedback (patient_id, dental_record_id);
                END IF;

                -- unique_feedback_per_medical_visit
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'unique_feedback_per_medical_visit') THEN
                    CREATE UNIQUE INDEX unique_feedback_per_medical_visit 
                    ON feedback_feedback (patient_id, medical_record_id) 
                    WHERE (medical_record_id IS NOT NULL);
                END IF;

                -- unique_feedback_per_dental_visit
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'unique_feedback_per_dental_visit') THEN
                    CREATE UNIQUE INDEX unique_feedback_per_dental_visit 
                    ON feedback_feedback (patient_id, dental_record_id) 
                    WHERE (dental_record_id IS NOT NULL);
                END IF;

                -- unique_general_feedback (now requires both record fields to be null)
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'unique_general_feedback') THEN
                    CREATE UNIQUE INDEX unique_general_feedback 
                    ON feedback_feedback (patient_id) 
                    WHERE (medical_record_id IS NULL AND dental_record_id IS NULL);
                END IF;
            END $$;
        """)
    elif vendor == 'sqlite':
        try:
            schema_editor.execute("ALTER TABLE feedback_feedback ADD COLUMN dental_record_id integer REFERENCES patients_dentalrecord(id) ON DELETE SET NULL;")
        except Exception: pass

class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_add_feedback_constraints'),
        ('patients', '0012_simplify_dental_and_consultation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='feedback',
                    name='unique_feedback_per_visit',
                ),
                migrations.RemoveConstraint(
                    model_name='feedback',
                    name='unique_general_feedback',
                ),
                # Add Field
                migrations.AddField(
                    model_name='feedback',
                    name='dental_record',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='patients.dentalrecord'),
                ),
                migrations.AddIndex(
                    model_name='feedback',
                    index=models.Index(fields=['patient', 'dental_record'], name='feedback_fe_patient_2c8f8b_idx'),
                ),
                migrations.AddConstraint(
                    model_name='feedback',
                    constraint=models.UniqueConstraint(condition=models.Q(('medical_record__isnull', False)), fields=('patient', 'medical_record'), name='unique_feedback_per_medical_visit'),
                ),
                migrations.AddConstraint(
                    model_name='feedback',
                    constraint=models.UniqueConstraint(condition=models.Q(('dental_record__isnull', False)), fields=('patient', 'dental_record'), name='unique_feedback_per_dental_visit'),
                ),
                migrations.AddConstraint(
                    model_name='feedback',
                    constraint=models.UniqueConstraint(condition=models.Q(('medical_record__isnull', True), ('dental_record__isnull', True)), fields=('patient',), name='unique_general_feedback'),
                ),
            ],
            database_operations=[
                migrations.RunPython(dental_feedback_db_logic, migrations.RunPython.noop),
            ]
        ),
    ]
