# Generated by Django 5.0.2 on 2026-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_add_dental_feedback'),
        ('patients', '0014_dentalrecord_feedback_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedback',
            name='unique_general_feedback',
        ),
        # migrations.RenameIndex(
        #     model_name='feedback',
        #     new_name='feedback_fe_patient_d5594a_idx',
        #     old_name='feedback_fe_patient_2c8f8b_idx',
        # ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('dental_record__isnull', True), ('medical_record__isnull', True)), fields=('patient',), name='unique_general_feedback'),
        ),
    ]
