# Generated by Django 5.0.2 on 2026-05-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_short'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedback',
            new_name='feedback_fe_patient_d5594a_idx',
            old_name='feedback_fe_patient_2c8f8b_idx',
        ),
    ]
